FROM node:21 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM builder AS launcher
WORKDIR /app
COPY --from=builder /app/build /app/build

EXPOSE 3000

CMD ["npm", "start"]
