apiVersion: v1
kind: Service
metadata:
  name: react-svc
  namespace: react-app
spec:
  ports:
  - port: 3000
    targetPort: 3000
    # nodePort: 30002
    protocol: TCP
    # name: 
  selector:
    app: react
    # tier: 
  type: NodePort